import 'bootstrap/dist/css/bootstrap.css'
import '@assets/styles/globals.scss'
import type { AppProps } from 'next/app'
import { Provider } from 'react-redux';
import store from '@app/store';
import moment from 'moment';
import { SessionProvider } from "next-auth/react"
import AppLayout from '@components/layout'
import Head from 'next/head';
// import 'moment/locale/en';
moment.locale('en');

const MyApp = ({ Component, pageProps: { session, ...pageProps } }: AppProps) => {
  return (
    <>
      <Head>
        <title>My Timetable App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400&family=Roboto:ital,wght@1,500&display=swap" rel="stylesheet" />
      </Head>
      <SessionProvider session={session}>
        <Provider store={store}>
          <AppLayout>
            <Component {...pageProps} />
          </AppLayout>
        </Provider>
      </SessionProvider>
    </>
  )
}
export default MyApp;
