import { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { Layout } from 'antd';
import AppHeader from '@src/components/header';
const { Content } = Layout;

const AppLayout: NextPage = ({ children }) => {
  return (
    <>
      <Head>
        <title>My Timetable App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout className="layout">
        <AppHeader />
        <Content>
          <main>
            {children}
          </main>
        </Content>
      </Layout>
    </>
  );
}

export default AppLayout;